### ISSUE TITLE
unable to show tf tree in 3D panel.

### ISSUE THREAD

**Issue by ZhengPan2014** [cruise-automation/webviz#444] opened 2020-05-28 09:47 UTC
as showed below, right part is rqt tf which indicates tf is good, left part is webviz, tf is not available, How to fix it? 
![image](https://user-images.githubusercontent.com/15884732/83125655-67b6ce80-a10a-11ea-90fd-7503de14990d.png)

**Comment by janpaul123** [comment] 2020-05-28 17:28
Do you have a bag that you can share for us to reproduce?

@vidaaudrey @davidswinegar maybe this is a bug with the new topic picker, can you follow up when we have a bag?

**Comment by vidaaudrey** [comment] 2020-05-28 18:43
Will do once @ZhengPan2014  have a bag for us to test.

**Comment by ZhengPan2014** [comment] 2020-05-29 02:02
> Will do once @ZhengPan2014 have a bag for us to test.

Yes, bag is available [here](https://pan.baidu.com/s/1zy6joV5yTtPYz3EAhv3dKw), access code is: xrx6.

**Comment by vidaaudrey** [comment] 2020-05-29 17:26
Looks like a bug. Will investigate and try to fix today.

**Comment by vidaaudrey** [comment] 2020-05-30 03:14
@ZhengPan2014 The problem is fixed now. Please let us know if you see any other issues. 
![image](https://user-images.githubusercontent.com/10999093/83318357-f0a43780-a1e8-11ea-9ef1-5d1efa3901a3.png)

**Closed by vidaaudrey** 2020-05-30 03:14 UTC
