### ISSUE TITLE
Colors switched for rgb pointcloud

### ISSUE THREAD

**Issue by shaeqahmed** [cruise-automation/webviz#293] opened 2019-12-18 22:33 UTC
Pointcloud viewer seems to be interpeting single 24bit value rgb channel/field as bgr.

Sample rosbag here: https://vision.in.tum.de/data/datasets/rgbd-dataset/download#freiburg3_cabinet

Relevant code block: 
https://github.com/cruise-automation/webviz/blob/2e7db3aafffec39b541728668c97ce7d83eee007/packages/webviz-core/src/panels/ThreeDimensionalViz/commands/Pointclouds/PointCloudBuilder.js#L174

Screenshot:
![bag](https://user-images.githubusercontent.com/13088492/71128720-bd25a180-21a2-11ea-8616-22054ccbd8b5.gif)

**Comment by janpaul123** [comment] 2019-12-19 01:07
cc @brianc @vidaaudrey @jtbandes

**Comment by jtbandes** [comment] 2019-12-20 20:52
Thanks for the report. I'm able to reproduce the issue and confirmed webviz's color handling differs from rviz.

**Comment by jtbandes** [comment] 2019-12-20 22:48
I suspect this has to do with our endianness handling. We don't use the `is_bigendian` field, but then again, rviz also seems to ignore it.

References:
https://github.com/ros-visualization/rviz/blob/070835c426b8982e304b38eb4a9c6eb221155d5f/src/rviz/default_plugin/point_cloud_common.cpp#L191
https://github.com/ros-visualization/rviz/blob/070835c426b8982e304b38eb4a9c6eb221155d5f/src/rviz/default_plugin/point_cloud_transformers.cpp#L366

**Comment by janpaul123** [comment] 2020-03-26 00:55
@shaeqahmed Update: it looks like someone internally is going to look into this soon. Btw, I'm trying to get to know our open source community better, and would love to learn more about what you use Webviz for. Could you perhaps shoot me an email at jp.posma@getcruise.com?

**Comment by janpaul123** [comment] 2020-04-09 18:46
This should be fixed now in #396. Let me know if you still see this issue!

**Closed by janpaul123** 2020-04-09 18:46 UTC
